#!/usr/bin/env bash
# derive the symbol -> library attribution for the vendored lib archive.
#   tools/darwin-symbol-map.sh <archive>      writes TOML to stdout
#
# a two-level-namespace darwin target requires every dynamic import to name the
# library that provides it. the imports arriving from a vendored static archive
# have no mach declaration to decorate, so they are claimed with `symbols` on
# the `[link.<entry>]` naming their library (see mach doc/manifest.md).
#
# the mapping is READ OFF THE SDK, never guessed. modern macOS keeps no on-disk
# framework binaries -- they live in the dyld shared cache -- so the authority
# is the SDK's .tbd text stubs, which list exactly what each library exports.
#
# `symbols` entries are SOURCE-LEVEL names: mach applies the target's leading
# underscore itself, so the Mach-O `___assert_rtn` is written `__assert_rtn`.
# this script strips exactly one leading underscore for that reason.
set -euo pipefail

# 检查是否至少传了一个参数
if [ "$#" -eq 0 ]; then
    echo "usage: $0 <archive.o> [<archive.a> ...]" >&2
    exit 1
fi

sdk=$(xcrun --sdk macosx --show-sdk-path)

candidates="
libSystem:usr/lib/libSystem.B.tbd
objc:usr/lib/libobjc.A.tbd
CoreFoundation:System/Library/Frameworks/CoreFoundation.framework/CoreFoundation.tbd
CoreGraphics:System/Library/Frameworks/CoreGraphics.framework/CoreGraphics.tbd
CoreServices:System/Library/Frameworks/CoreServices.framework/CoreServices.tbd
IOKit:System/Library/Frameworks/IOKit.framework/IOKit.tbd
CoreVideo:System/Library/Frameworks/CoreVideo.framework/CoreVideo.tbd
OpenGL:System/Library/Frameworks/OpenGL.framework/OpenGL.tbd
Foundation:System/Library/Frameworks/Foundation.framework/Foundation.tbd
AppKit:System/Library/Frameworks/AppKit.framework/AppKit.tbd
Cocoa:System/Library/Frameworks/Cocoa.framework/Cocoa.tbd
"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# 初始化空文件
: > "$work/undef.all"
: > "$work/defined"

# 遍历所有传入的文件参数，汇总符号
for archive in "$@"; do
    [ -f "$archive" ] || { echo "警告: 找不到文件 $archive" >&2; continue; }
    
    echo "# 正在提取: $archive" >&2
    
    # 加上 || true 防止某个文件没有符号时 grep 返回非零导致脚本退出
    if ! nm -u "$archive" 2>/dev/null | awk '{print $NF}' | grep '^_' >> "$work/undef.all" 2>/dev/null; then
        echo "#   -> 提示: $archive 没有未定义符号或无法读取 (如果是 bitcode 格式则需先编译为纯目标文件)" >&2
    fi
    
    nm -g --defined-only "$archive" 2>/dev/null | awk '{print $NF}' | grep '^_' >> "$work/defined" 2>/dev/null || true
done

# 排序去重
sort -u -o "$work/undef.all" "$work/undef.all"
sort -u -o "$work/defined" "$work/defined"
comm -23 "$work/undef.all" "$work/defined" > "$work/undef"

echo "# generated by $0 -- do not hand-edit" >&2
echo "# archives:  $*" >&2
echo "# sdk:      $sdk" >&2
echo "# undefined: $(wc -l < "$work/undef.all") total, $(wc -l < "$work/defined") defined here, $(wc -l < "$work/undef") to attribute" >&2

cp "$work/undef" "$work/remaining"
: > "$work/out"

# 遍历系统库，匹配符号
for entry in $candidates; do
    name=${entry%%:*}
    tbd=$sdk/${entry#*:}
    [ -f "$tbd" ] || { echo "# MISSING stub for $name: $tbd" >&2; continue; }

    {
        grep -oE '_[A-Za-z0-9_$.]+' "$tbd"
        awk '
            /objc-classes/ { inobjc = 1 }
            inobjc {
                line = $0
                gsub(/objc-classes/, "", line)
                n = split(line, tok, /[^A-Za-z0-9_]+/)
                for (i = 1; i <= n; i++)
                    if (tok[i] != "") {
                        print "_OBJC_CLASS_$_" tok[i]
                        print "_OBJC_METACLASS_$_" tok[i]
                    }
                if (index($0, "]") > 0) inobjc = 0
            }
        ' "$tbd"
    } | sort -u > "$work/exports.$name"
    comm -12 "$work/remaining" "$work/exports.$name" > "$work/claim.$name"

    if [ -s "$work/claim.$name" ]; then
        printf '%s %s\n' "$name" "$(wc -l < "$work/claim.$name" | tr -d ' ')" >> "$work/out"
        comm -23 "$work/remaining" "$work/claim.$name" > "$work/next"
        mv "$work/next" "$work/remaining"
    fi
done

# -------------------------------------------------------------
# 核心自动化：将所有未归属的符号自动追加到 libSystem 中
# 因为 macOS 的私有底层符号都在运行时由 libSystem 提供
# -------------------------------------------------------------
if [ -s "$work/remaining" ]; then
    if [ -f "$work/claim.libSystem" ]; then
        cat "$work/remaining" >> "$work/claim.libSystem"
    else
        cp "$work/remaining" "$work/claim.libSystem"
    fi
    
    # 去重并更新 libSystem 的 claim 文件
    sort -u -o "$work/claim.libSystem" "$work/claim.libSystem"
    
    # 更新 libSystem 的统计记录
    grep -v '^libSystem ' "$work/out" > "$work/out.tmp" && mv "$work/out.tmp" "$work/out"
    count=$(wc -l < "$work/claim.libSystem" | tr -d ' ')
    printf 'libSystem %s\n' "$count" >> "$work/out"
    
    echo "# 注意: 将 $(wc -l < "$work/remaining" | tr -d ' ') 个私有/未识别符号自动归并到 libSystem" >&2
    : > "$work/remaining" # 清空剩余符号
fi

# 输出 TOML 配置，带 70 宽度排版
while read -r name count; do
    echo "# $name provides $count of the archive's imports"
    echo "symbols_for_$name = ["
    sed 's/^_//' "$work/claim.$name" | awk '
    {
        item = "\"" $0 "\", "
        if (line == "") {
            line = "    " item
        } else if (length(line) + length(item) > 72) {
            print line
            line = "    " item
        } else {
            line = line item
        }
    }
    END {
        if (length(line) > 0) {
            sub(/, $/, "", line)
            print line
        }
    }'
    echo "]"
    echo
done < "$work/out"
